service: refacil-test
package:
  individually: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  architecture: arm64
  stage: release
  profile: keybe
  timeout: 60
  lambdaHashingVersion: 20201221
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    URLConsulta: ${env:URLConsulta, 'https://www.datos.gov.co/resource/gt2j-8ykr.json'}
    Host: ${env:Host, 'refacil.cuazzhdbtbk0.us-east-1.rds.amazonaws.com'}
    UserDB:  ${env:UserDB, 'postgres'}
    DB:  ${env:DB, 'refacildb'}
    PASS:  ${env:PASS, 'C0l0mb1a'}
    REGION : us-east-1
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - xray:PutTelemetryRecords
            - xray:PutTraceSegments
          Resource: '*'              
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.[t|j]s
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5
  serverless-offline:
    httpPort: 4000
functions: 
  ${file(./yml/functions.yml)}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function
  
